// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20260303135229_novaspermissoesnotafiscal")]
    partial class novaspermissoesnotafiscal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountDigit")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("AgencyDigit")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("AgencyNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HolderDocument")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("HolderType")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PixKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_bankAccount", (string)null);
                });

            modelBuilder.Entity("Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Complement")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameCity")
                        .HasColumnType("text");

                    b.Property<string>("NameState")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_client", (string)null);
                });

            modelBuilder.Entity("Model.Closure.Closures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateInit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<string>("LatFinal")
                        .HasColumnType("text");

                    b.Property<string>("LatInit")
                        .HasColumnType("text");

                    b.Property<string>("LongFinal")
                        .HasColumnType("text");

                    b.Property<string>("LongInit")
                        .HasColumnType("text");

                    b.Property<decimal>("Odometer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OdometerFinal")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("kilometerTraveled")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdSalesman");

                    b.ToTable("tb_closures", (string)null);
                });

            modelBuilder.Entity("Model.Closure.ClosuresDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdClosures")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdClosures");

                    b.ToTable("tb_closuresDetail", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Diferenca")
                        .HasColumnType("numeric");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("SaldoCalculado")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_box", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_budget", (string)null);
                });

            modelBuilder.Entity("Model.Moves.BudgetItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdBudget")
                        .HasColumnType("integer");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int>("TypeItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdBudget");

                    b.ToTable("tb_budgetItems", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Financial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("BoxId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinancialStatus")
                        .HasColumnType("integer");

                    b.Property<int>("FinancialType")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int?>("IdCostCenter")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSale")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSaleItems")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<int?>("IdService")
                        .HasColumnType("integer");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<bool>("commission")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdCostCenter");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdSaleItems");

                    b.HasIndex("IdSalesman");

                    b.HasIndex("IdService");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("tb_financial", (string)null);
                });

            modelBuilder.Entity("Model.Moves.FinancialResources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNewFinancial")
                        .HasColumnType("integer");

                    b.Property<int>("IdRefOrigin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tb_financialResources", (string)null);
                });

            modelBuilder.Entity("Model.Moves.PlanCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastPayment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany")
                        .IsUnique();

                    b.ToTable("tb_planCompany", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSeller")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdSeller");

                    b.ToTable("tb_sale", (string)null);
                });

            modelBuilder.Entity("Model.Moves.SaleItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableRecurrence")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdSale")
                        .HasColumnType("integer");

                    b.Property<int?>("IdService")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecurringAmount")
                        .HasColumnType("integer");

                    b.Property<int>("TypeItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdService");

                    b.ToTable("tb_saleItems", (string)null);
                });

            modelBuilder.Entity("Model.Moves.ServicesProvision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("IdBudget")
                        .HasColumnType("integer");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdBudget");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_serviceProvision", (string)null);
                });

            modelBuilder.Entity("Model.Moves.ServicesProvisionItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int>("IdServiceProvision")
                        .HasColumnType("integer");

                    b.Property<int>("TypeItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdServiceProvision");

                    b.ToTable("tb_servicesProvisionItems", (string)null);
                });

            modelBuilder.Entity("Model.Moves.SharedCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionDay")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableSharedCommission")
                        .HasColumnType("boolean");

                    b.Property<int>("IdCostCenter")
                        .HasColumnType("integer");

                    b.Property<int>("IdSaleItems")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<string>("NameSeller")
                        .HasColumnType("text");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<int>("RecurringAmount")
                        .HasColumnType("integer");

                    b.Property<int>("TypeDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCostCenter");

                    b.HasIndex("IdSaleItems");

                    b.HasIndex("IdSalesman");

                    b.ToTable("tb_sharedCommission", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdProduct");

                    b.ToTable("tb_stock", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionDay")
                        .HasColumnType("integer");

                    b.Property<int>("IdCostCenter")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<int?>("IdService")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TypeDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCostCenter");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSalesman");

                    b.HasIndex("IdService");

                    b.ToTable("tb_commission", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Cellphone")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("CommercialPhone")
                        .HasColumnType("text");

                    b.Property<string>("CorporateName")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Ie")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tb_company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorporateName = "Empresa Padrão",
                            Guid = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Model.Registrations.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_costCenter", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.DescriptionFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameProduct")
                        .HasColumnType("text");

                    b.Property<string>("descriptionProduct")
                        .HasColumnType("text");

                    b.Property<int?>("groupItems")
                        .HasColumnType("integer");

                    b.Property<int>("idCompany")
                        .HasColumnType("integer");

                    b.Property<string>("valueProduct")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("idCompany");

                    b.ToTable("tb_descriptionFiles", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.DetailsService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdServiceProvided")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdServiceProvided");

                    b.ToTable("tb_detailsService", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileThumb")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Files")
                        .HasColumnType("bytea");

                    b.Property<int>("IdDescriptionFiles")
                        .HasColumnType("integer");

                    b.Property<string>("MyProperty")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDescriptionFiles");

                    b.ToTable("tb_file", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.FiscalConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AutorizacaoASO")
                        .HasColumnType("boolean")
                        .HasColumnName("AutorizacaoASO");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("tb_fiscalConfiguration", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.NFeEmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComapanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NaturezaOperacaoId")
                        .HasColumnType("integer");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<bool>("Sent")
                        .HasColumnType("boolean");

                    b.Property<string>("Serie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StatusNfe")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.Property<int>("TryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComapanyId");

                    b.HasIndex("NaturezaOperacaoId");

                    b.HasIndex("SaleId");

                    b.ToTable("tb_nfeEmission", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.NaturezaOperacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cfop")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConsumidorFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("MovimentaEstoque")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Cfop", "TipoDocumento")
                        .IsUnique();

                    b.ToTable("tb_naturezaOperacao", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_paymentMethod", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tb_permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cadastros",
                            Code = 1,
                            Name = "Visualizar Empresa"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cadastros",
                            Code = 2,
                            Name = "Editar Empresa"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Cadastros",
                            Code = 10,
                            Name = "Visualizar Produtos"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Cadastros",
                            Code = 11,
                            Name = "Criar Produto"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Cadastros",
                            Code = 12,
                            Name = "Editar Produto"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Cadastros",
                            Code = 13,
                            Name = "Excluir Produto"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cadastros",
                            Code = 20,
                            Name = "Visualizar Clientes"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Cadastros",
                            Code = 21,
                            Name = "Criar Cliente"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Cadastros",
                            Code = 22,
                            Name = "Editar Cliente"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Vendas",
                            Code = 30,
                            Name = "Visualizar Vendas"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Vendas",
                            Code = 31,
                            Name = "Criar Venda"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Vendas",
                            Code = 32,
                            Name = "Cancelar Venda"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Vendas",
                            Code = 82,
                            Name = "Alterar Venda"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Financeiro",
                            Code = 40,
                            Name = "Visualizar Financeiro"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Financeiro",
                            Code = 41,
                            Name = "Editar Financeiro"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Financeiro",
                            Code = 88,
                            Name = "Criar financeiro"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Estoque",
                            Code = 50,
                            Name = "Visualizar Estoque"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Estoque",
                            Code = 51,
                            Name = "Ajustar Estoque"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Estoque",
                            Code = 93,
                            Name = "Criar Estoque"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Estoque",
                            Code = 94,
                            Name = "Deletar Estoque"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Renegociação",
                            Code = 60,
                            Name = "Visualizar Renegociações"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Renegociação",
                            Code = 61,
                            Name = "Criar Renegociação"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Usuários",
                            Code = 70,
                            Name = "Visualizar Usuários"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Usuários",
                            Code = 71,
                            Name = "Gerenciar Usuários"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Usuários",
                            Code = 72,
                            Description = "Pode atribuir permissões a outros usuários",
                            Name = "Gerenciar Permissões"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Cadastros",
                            Code = 80,
                            Name = "Visualizar Formas de Pagamento"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Cadastros",
                            Code = 81,
                            Name = "Gerenciar Formas de Pagamento"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Cadastros",
                            Code = 84,
                            Name = "Criar conta bancária"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Cadastros",
                            Code = 85,
                            Name = "editar conta bancária"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Cadastros",
                            Code = 83,
                            Name = "visualizar conta bancária"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Financeiro",
                            Code = 86,
                            Name = "Ver caixa"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Financeiro",
                            Code = 87,
                            Name = "Abrir caixa"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Cadastros",
                            Code = 89,
                            Name = "Visualizar Configurações de Nota Fiscal"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Cadastros",
                            Code = 90,
                            Name = "Criar Configurações de Nota Fiscal"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Cadastros",
                            Code = 91,
                            Name = "Editar Configurações de Nota Fiscal"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Cadastros",
                            Code = 92,
                            Name = "Cancelar Configurações de Nota Fiscal"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Notas",
                            Code = 95,
                            Name = "Visualizar Notas Fiscais"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Notas",
                            Code = 96,
                            Name = "Criar Notas Fiscais"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Notas",
                            Code = 97,
                            Name = "Cancelar Notas Fiscais"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Notas",
                            Code = 98,
                            Name = "Editar Notas Fiscais"
                        });
                });

            modelBuilder.Entity("Model.Registrations.PhasesProspects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProspects")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProspects");

                    b.ToTable("tb_phasesProspects", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageBytes")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_product", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Prospects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_prospects", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Salesman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameCity")
                        .HasColumnType("text");

                    b.Property<string>("NameState")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_salesman", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.ServiceProvided", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Capacity")
                        .HasColumnType("text");

                    b.Property<string>("Deadline")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_ServiceProvided", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_userPermission", (string)null);
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CellPhone")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("TokenVerify")
                        .HasColumnType("text");

                    b.Property<int>("TypeUser")
                        .HasColumnType("integer");

                    b.Property<bool>("VerifiedEmail")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@padrao.com.br",
                            IdCompany = 1,
                            Name = "Admin",
                            Password = "",
                            TypeUser = 0,
                            VerifiedEmail = false
                        });
                });

            modelBuilder.Entity("Model.BankAccount", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("BankAccounts")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Client", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Closure.Closures", b =>
                {
                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Closures")
                        .HasForeignKey("IdSalesman")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Model.Closure.ClosuresDetail", b =>
                {
                    b.HasOne("Model.Closure.Closures", "Closures")
                        .WithMany("ClosuresDetails")
                        .HasForeignKey("IdClosures")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Closures");
                });

            modelBuilder.Entity("Model.Moves.Box", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Boxes")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.Budget", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Budgets")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.BudgetItems", b =>
                {
                    b.HasOne("Model.Moves.Budget", "Budget")
                        .WithMany("BudgetItems")
                        .HasForeignKey("IdBudget")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Model.Moves.Financial", b =>
                {
                    b.HasOne("Model.BankAccount", "BankAccount")
                        .WithMany("Financials")
                        .HasForeignKey("BankAccountId");

                    b.HasOne("Model.Client", "Client")
                        .WithMany("Financials")
                        .HasForeignKey("IdClient");

                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Financials")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.CostCenter", "CostCenter")
                        .WithMany("Financials")
                        .HasForeignKey("IdCostCenter");

                    b.HasOne("Model.Moves.Box", "Box")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("Financials")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Moves.Sale", "Sale")
                        .WithMany("Financials")
                        .HasForeignKey("IdSale");

                    b.HasOne("Model.Moves.SaleItems", "SaleItems")
                        .WithMany("Financials")
                        .HasForeignKey("IdSaleItems");

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Financials")
                        .HasForeignKey("IdSalesman");

                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("Financials")
                        .HasForeignKey("IdService");

                    b.HasOne("Model.Registrations.PaymentMethod", "PaymentMethod")
                        .WithMany("Financials")
                        .HasForeignKey("PaymentMethodId");

                    b.Navigation("BankAccount");

                    b.Navigation("Box");

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("CostCenter");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("SaleItems");

                    b.Navigation("Salesman");

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Moves.PlanCompany", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithOne("PlanCompany")
                        .HasForeignKey("Model.Moves.PlanCompany", "IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.Sale", b =>
                {
                    b.HasOne("Model.Client", "Client")
                        .WithMany("Sale")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Sale")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Sale")
                        .HasForeignKey("IdSeller");

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Model.Moves.SaleItems", b =>
                {
                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Moves.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("SaleItems")
                        .HasForeignKey("IdService");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Moves.ServicesProvision", b =>
                {
                    b.HasOne("Model.Moves.Budget", "Budget")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("IdBudget");

                    b.HasOne("Model.Client", "Client")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.ServicesProvisionItems", b =>
                {
                    b.HasOne("Model.Moves.ServicesProvision", "ServiceProvision")
                        .WithMany("ServicesProvisionItems")
                        .HasForeignKey("IdServiceProvision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvision");
                });

            modelBuilder.Entity("Model.Moves.SharedCommission", b =>
                {
                    b.HasOne("Model.Registrations.CostCenter", "CostCenter")
                        .WithMany("SharedCommissions")
                        .HasForeignKey("IdCostCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Moves.SaleItems", "SaleItems")
                        .WithMany("SharedCommissions")
                        .HasForeignKey("IdSaleItems")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("SharedCommissions")
                        .HasForeignKey("IdSalesman")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostCenter");

                    b.Navigation("SaleItems");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Model.Moves.Stock", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Stocks")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Model.Registrations.Commission", b =>
                {
                    b.HasOne("Model.Registrations.CostCenter", "CostCenter")
                        .WithMany("Commissions")
                        .HasForeignKey("IdCostCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("Commissions")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Commissions")
                        .HasForeignKey("IdSalesman")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("Commissions")
                        .HasForeignKey("IdService");

                    b.Navigation("CostCenter");

                    b.Navigation("Product");

                    b.Navigation("Salesman");

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Registrations.CostCenter", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("CostCenters")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.DescriptionFiles", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("DescriptionFiles")
                        .HasForeignKey("idCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.DetailsService", b =>
                {
                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("Details")
                        .HasForeignKey("IdServiceProvided")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Registrations.File", b =>
                {
                    b.HasOne("Model.Registrations.DescriptionFiles", "DescriptionFiles")
                        .WithMany("Files")
                        .HasForeignKey("IdDescriptionFiles")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DescriptionFiles");
                });

            modelBuilder.Entity("Model.Registrations.FiscalConfiguration", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithOne("FiscalConfiguration")
                        .HasForeignKey("Model.Registrations.FiscalConfiguration", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Model.Registrations.CertificadoDigital", "CertificadoDigital", b1 =>
                        {
                            b1.Property<int>("FiscalConfigurationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Arquivo")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Certificado_Arquivo");

                            b1.Property<string>("Senha")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Certificado_Senha");

                            b1.HasKey("FiscalConfigurationId");

                            b1.ToTable("tb_fiscalConfiguration");

                            b1.WithOwner()
                                .HasForeignKey("FiscalConfigurationId");
                        });

                    b.OwnsOne("Model.Registrations.Csc", "Csc", b1 =>
                        {
                            b1.Property<int>("FiscalConfigurationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Identificador")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Csc_Identificador");

                            b1.Property<string>("Valor")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Csc_Valor");

                            b1.HasKey("FiscalConfigurationId");

                            b1.ToTable("tb_fiscalConfiguration");

                            b1.WithOwner()
                                .HasForeignKey("FiscalConfigurationId");
                        });

                    b.OwnsOne("Model.Registrations.Emitente", "Emitente", b1 =>
                        {
                            b1.Property<int>("FiscalConfigurationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Cnpj")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Emitente_Cnpj");

                            b1.Property<string>("Cpf")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Emitente_Cpf");

                            b1.Property<string>("Fantasia")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("Emitente_Fantasia");

                            b1.Property<string>("InscricaoEstadual")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Emitente_InscricaoEstadual");

                            b1.Property<string>("RazaoSocial")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("Emitente_RazaoSocial");

                            b1.HasKey("FiscalConfigurationId");

                            b1.ToTable("tb_fiscalConfiguration");

                            b1.WithOwner()
                                .HasForeignKey("FiscalConfigurationId");

                            b1.OwnsOne("Model.Registrations.Contato", "EmitenteContato", b2 =>
                                {
                                    b2.Property<int>("EmitenteFiscalConfigurationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Telefone")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Emitente_Telefone");

                                    b2.HasKey("EmitenteFiscalConfigurationId");

                                    b2.ToTable("tb_fiscalConfiguration");

                                    b2.WithOwner()
                                        .HasForeignKey("EmitenteFiscalConfigurationId");
                                });

                            b1.OwnsOne("Model.Registrations.Endereco", "EmitenteEndereco", b2 =>
                                {
                                    b2.Property<int>("EmitenteFiscalConfigurationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Bairro")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("Emitente_Bairro");

                                    b2.Property<string>("Cep")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("Emitente_Cep");

                                    b2.Property<string>("Cidade")
                                        .HasMaxLength(150)
                                        .HasColumnType("character varying(150)")
                                        .HasColumnName("Emitente_Cidade");

                                    b2.Property<string>("CodigoCidade")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Emitente_CodigoCidade");

                                    b2.Property<string>("Complemento")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("Emitente_Complemento");

                                    b2.Property<string>("Logradouro")
                                        .HasMaxLength(250)
                                        .HasColumnType("character varying(250)")
                                        .HasColumnName("Emitente_Logradouro");

                                    b2.Property<string>("Numero")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Emitente_Numero");

                                    b2.Property<string>("Uf")
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("Emitente_Uf");

                                    b2.HasKey("EmitenteFiscalConfigurationId");

                                    b2.ToTable("tb_fiscalConfiguration");

                                    b2.WithOwner()
                                        .HasForeignKey("EmitenteFiscalConfigurationId");
                                });

                            b1.OwnsOne("Model.Registrations.RegimeTributario", "RegimeTributario", b2 =>
                                {
                                    b2.Property<int>("EmitenteFiscalConfigurationId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Crt")
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("Emitente_Crt");

                                    b2.HasKey("EmitenteFiscalConfigurationId");

                                    b2.ToTable("tb_fiscalConfiguration");

                                    b2.WithOwner()
                                        .HasForeignKey("EmitenteFiscalConfigurationId");
                                });

                            b1.Navigation("EmitenteContato")
                                .IsRequired();

                            b1.Navigation("EmitenteEndereco")
                                .IsRequired();

                            b1.Navigation("RegimeTributario")
                                .IsRequired();
                        });

                    b.OwnsOne("Model.Registrations.NumeracaoDocumentos", "NumeracaoDocumentos", b1 =>
                        {
                            b1.Property<int>("FiscalConfigurationId")
                                .HasColumnType("integer");

                            b1.HasKey("FiscalConfigurationId");

                            b1.ToTable("tb_fiscalConfiguration");

                            b1.WithOwner()
                                .HasForeignKey("FiscalConfigurationId");

                            b1.OwnsOne("Model.Registrations.NumeracaoItem", "Nfce", b2 =>
                                {
                                    b2.Property<int>("NumeracaoDocumentosFiscalConfigurationId")
                                        .HasColumnType("integer");

                                    b2.Property<long>("NumeroInicial")
                                        .HasColumnType("bigint")
                                        .HasColumnName("Nfce_NumeroInicial");

                                    b2.Property<string>("Serie")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Nfce_Serie");

                                    b2.HasKey("NumeracaoDocumentosFiscalConfigurationId");

                                    b2.ToTable("tb_fiscalConfiguration");

                                    b2.WithOwner()
                                        .HasForeignKey("NumeracaoDocumentosFiscalConfigurationId");
                                });

                            b1.OwnsOne("Model.Registrations.NumeracaoItem", "Nfe", b2 =>
                                {
                                    b2.Property<int>("NumeracaoDocumentosFiscalConfigurationId")
                                        .HasColumnType("integer");

                                    b2.Property<long>("NumeroInicial")
                                        .HasColumnType("bigint")
                                        .HasColumnName("Nfe_NumeroInicial");

                                    b2.Property<string>("Serie")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Nfe_Serie");

                                    b2.HasKey("NumeracaoDocumentosFiscalConfigurationId");

                                    b2.ToTable("tb_fiscalConfiguration");

                                    b2.WithOwner()
                                        .HasForeignKey("NumeracaoDocumentosFiscalConfigurationId");
                                });

                            b1.Navigation("Nfce")
                                .IsRequired();

                            b1.Navigation("Nfe")
                                .IsRequired();
                        });

                    b.Navigation("CertificadoDigital")
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Csc")
                        .IsRequired();

                    b.Navigation("Emitente")
                        .IsRequired();

                    b.Navigation("NumeracaoDocumentos")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Registrations.NFeEmission", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("NFeEmissions")
                        .HasForeignKey("ComapanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.NaturezaOperacao", "NaturezaOperacao")
                        .WithMany("NFeEmissions")
                        .HasForeignKey("NaturezaOperacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Moves.Sale", "Sale")
                        .WithMany("NFeEmissions")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("NaturezaOperacao");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Model.Registrations.NaturezaOperacao", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("NaturezaOperacoes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Model.Registrations.ConfiguracaoTributaria", "ConfiguracaoTributaria", b1 =>
                        {
                            b1.Property<int>("NaturezaOperacaoId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("AliquotaCBS")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaCBS");

                            b1.Property<decimal>("AliquotaCOFINS")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaCOFINS");

                            b1.Property<decimal>("AliquotaIBS")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaIBS");

                            b1.Property<decimal>("AliquotaICMS")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaICMS");

                            b1.Property<decimal>("AliquotaIPI")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaIPI");

                            b1.Property<decimal>("AliquotaIS")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaIS");

                            b1.Property<decimal>("AliquotaISSQN")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaISSQN");

                            b1.Property<decimal>("AliquotaPIS")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("AliquotaPIS");

                            b1.Property<bool>("AplicarCBS")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarCBS");

                            b1.Property<bool>("AplicarCOFINS")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarCOFINS");

                            b1.Property<bool>("AplicarIBS")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarIBS");

                            b1.Property<bool>("AplicarICMS")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarICMS");

                            b1.Property<bool>("AplicarIPI")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarIPI");

                            b1.Property<bool>("AplicarIS")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarIS");

                            b1.Property<bool>("AplicarISSQN")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarISSQN");

                            b1.Property<bool>("AplicarPIS")
                                .HasColumnType("boolean")
                                .HasColumnName("AplicarPIS");

                            b1.Property<string>("CstCBS")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CstCBS");

                            b1.Property<string>("CstCOFINS")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CstCOFINS");

                            b1.Property<string>("CstIBS")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CstIBS");

                            b1.Property<string>("CstICMS")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CstICMS");

                            b1.Property<string>("CstIPI")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CstIPI");

                            b1.Property<string>("CstPIS")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CstPIS");

                            b1.Property<bool>("ReduzirBaseICMS")
                                .HasColumnType("boolean")
                                .HasColumnName("ReduzirBaseICMS");

                            b1.HasKey("NaturezaOperacaoId");

                            b1.ToTable("tb_naturezaOperacao");

                            b1.WithOwner()
                                .HasForeignKey("NaturezaOperacaoId");
                        });

                    b.Navigation("Company");

                    b.Navigation("ConfiguracaoTributaria");
                });

            modelBuilder.Entity("Model.Registrations.PaymentMethod", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.PhasesProspects", b =>
                {
                    b.HasOne("Model.Registrations.Prospects", "Prospects")
                        .WithMany("PhasesProspects")
                        .HasForeignKey("IdProspects")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prospects");
                });

            modelBuilder.Entity("Model.Registrations.Product", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.Prospects", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Prospects")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.Salesman", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Salesmen")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.ServiceProvided", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("ServiceProvideds")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.UserPermission", b =>
                {
                    b.HasOne("Model.Registrations.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.BankAccount", b =>
                {
                    b.Navigation("Financials");
                });

            modelBuilder.Entity("Model.Client", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("Sale");

                    b.Navigation("ServiceProvisions");
                });

            modelBuilder.Entity("Model.Closure.Closures", b =>
                {
                    b.Navigation("ClosuresDetails");
                });

            modelBuilder.Entity("Model.Moves.Box", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Model.Moves.Budget", b =>
                {
                    b.Navigation("BudgetItems");

                    b.Navigation("ServiceProvisions");
                });

            modelBuilder.Entity("Model.Moves.Sale", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("NFeEmissions");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Model.Moves.SaleItems", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("SharedCommissions");
                });

            modelBuilder.Entity("Model.Moves.ServicesProvision", b =>
                {
                    b.Navigation("ServicesProvisionItems");
                });

            modelBuilder.Entity("Model.Registrations.Company", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Boxes");

                    b.Navigation("Budgets");

                    b.Navigation("Clients");

                    b.Navigation("CostCenters");

                    b.Navigation("DescriptionFiles");

                    b.Navigation("Financials");

                    b.Navigation("FiscalConfiguration");

                    b.Navigation("NFeEmissions");

                    b.Navigation("NaturezaOperacoes");

                    b.Navigation("PaymentMethods");

                    b.Navigation("PlanCompany");

                    b.Navigation("Products");

                    b.Navigation("Prospects");

                    b.Navigation("Sale");

                    b.Navigation("Salesmen");

                    b.Navigation("ServiceProvideds");

                    b.Navigation("ServiceProvisions");

                    b.Navigation("Stocks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Model.Registrations.CostCenter", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Financials");

                    b.Navigation("SharedCommissions");
                });

            modelBuilder.Entity("Model.Registrations.DescriptionFiles", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Model.Registrations.NaturezaOperacao", b =>
                {
                    b.Navigation("NFeEmissions");
                });

            modelBuilder.Entity("Model.Registrations.PaymentMethod", b =>
                {
                    b.Navigation("Financials");
                });

            modelBuilder.Entity("Model.Registrations.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Model.Registrations.Product", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Financials");

                    b.Navigation("SaleItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Model.Registrations.Prospects", b =>
                {
                    b.Navigation("PhasesProspects");
                });

            modelBuilder.Entity("Model.Registrations.Salesman", b =>
                {
                    b.Navigation("Closures");

                    b.Navigation("Commissions");

                    b.Navigation("Financials");

                    b.Navigation("Sale");

                    b.Navigation("SharedCommissions");
                });

            modelBuilder.Entity("Model.Registrations.ServiceProvided", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Details");

                    b.Navigation("Financials");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
