// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20260202133246_linkfinancicalresource")]
    partial class linkfinancicalresource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Complement")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameCity")
                        .HasColumnType("text");

                    b.Property<string>("NameState")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_client", (string)null);
                });

            modelBuilder.Entity("Model.Closure.Closures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateInit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<string>("LatFinal")
                        .HasColumnType("text");

                    b.Property<string>("LatInit")
                        .HasColumnType("text");

                    b.Property<string>("LongFinal")
                        .HasColumnType("text");

                    b.Property<string>("LongInit")
                        .HasColumnType("text");

                    b.Property<decimal>("Odometer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OdometerFinal")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("kilometerTraveled")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdSalesman");

                    b.ToTable("tb_closures", (string)null);
                });

            modelBuilder.Entity("Model.Closure.ClosuresDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdClosures")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdClosures");

                    b.ToTable("tb_closuresDetail", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Diferenca")
                        .HasColumnType("numeric");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("SaldoCalculado")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tb_box", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_budget", (string)null);
                });

            modelBuilder.Entity("Model.Moves.BudgetItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdBudget")
                        .HasColumnType("integer");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int>("TypeItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdBudget");

                    b.ToTable("tb_budgetItems", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Financial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoxId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinancialStatus")
                        .HasColumnType("integer");

                    b.Property<int>("FinancialType")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int?>("IdCostCenter")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSale")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSaleItems")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<int?>("IdService")
                        .HasColumnType("integer");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<bool>("commission")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdCostCenter");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdSaleItems");

                    b.HasIndex("IdSalesman");

                    b.HasIndex("IdService");

                    b.ToTable("tb_financial", (string)null);
                });

            modelBuilder.Entity("Model.Moves.FinancialResources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNewFinancial")
                        .HasColumnType("integer");

                    b.Property<int>("IdRefOrigin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tb_financialResources", (string)null);
                });

            modelBuilder.Entity("Model.Moves.PlanCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastPayment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany")
                        .IsUnique();

                    b.ToTable("tb_planCompany", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSeller")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdSeller");

                    b.ToTable("tb_sale", (string)null);
                });

            modelBuilder.Entity("Model.Moves.SaleItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableRecurrence")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdSale")
                        .HasColumnType("integer");

                    b.Property<int?>("IdService")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecurringAmount")
                        .HasColumnType("integer");

                    b.Property<int>("TypeItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSale");

                    b.HasIndex("IdService");

                    b.ToTable("tb_saleItems", (string)null);
                });

            modelBuilder.Entity("Model.Moves.ServicesProvision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("IdBudget")
                        .HasColumnType("integer");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdBudget");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_serviceProvision", (string)null);
                });

            modelBuilder.Entity("Model.Moves.ServicesProvisionItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int>("IdServiceProvision")
                        .HasColumnType("integer");

                    b.Property<int>("TypeItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdServiceProvision");

                    b.ToTable("tb_servicesProvisionItems", (string)null);
                });

            modelBuilder.Entity("Model.Moves.SharedCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionDay")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableSharedCommission")
                        .HasColumnType("boolean");

                    b.Property<int>("IdCostCenter")
                        .HasColumnType("integer");

                    b.Property<int>("IdSaleItems")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<string>("NameSeller")
                        .HasColumnType("text");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<int>("RecurringAmount")
                        .HasColumnType("integer");

                    b.Property<int>("TypeDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCostCenter");

                    b.HasIndex("IdSaleItems");

                    b.HasIndex("IdSalesman");

                    b.ToTable("tb_sharedCommission", (string)null);
                });

            modelBuilder.Entity("Model.Moves.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdProduct");

                    b.ToTable("tb_stock", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionDay")
                        .HasColumnType("integer");

                    b.Property<int>("IdCostCenter")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalesman")
                        .HasColumnType("integer");

                    b.Property<int?>("IdService")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TypeDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCostCenter");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSalesman");

                    b.HasIndex("IdService");

                    b.ToTable("tb_commission", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Cellphone")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("CommercialPhone")
                        .HasColumnType("text");

                    b.Property<string>("CorporateName")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Ie")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tb_company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorporateName = "Empresa Padrão",
                            Guid = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Model.Registrations.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_costCenter", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.DescriptionFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameProduct")
                        .HasColumnType("text");

                    b.Property<string>("descriptionProduct")
                        .HasColumnType("text");

                    b.Property<int?>("groupItems")
                        .HasColumnType("integer");

                    b.Property<int>("idCompany")
                        .HasColumnType("integer");

                    b.Property<string>("valueProduct")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("idCompany");

                    b.ToTable("tb_descriptionFiles", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.DetailsService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdServiceProvided")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdServiceProvided");

                    b.ToTable("tb_detailsService", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<byte[]>("FileThumb")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Files")
                        .HasColumnType("bytea");

                    b.Property<int>("IdDescriptionFiles")
                        .HasColumnType("integer");

                    b.Property<string>("MyProperty")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDescriptionFiles");

                    b.ToTable("tb_file", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.PhasesProspects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProspects")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProspects");

                    b.ToTable("tb_phasesProspects", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageBytes")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_product", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Prospects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_prospects", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.Salesman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameCity")
                        .HasColumnType("text");

                    b.Property<string>("NameState")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_salesman", (string)null);
                });

            modelBuilder.Entity("Model.Registrations.ServiceProvided", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Capacity")
                        .HasColumnType("text");

                    b.Property<string>("Deadline")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_ServiceProvided", (string)null);
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CellPhone")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("TokenVerify")
                        .HasColumnType("text");

                    b.Property<int>("TypeUser")
                        .HasColumnType("integer");

                    b.Property<bool>("VerifiedEmail")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdCompany");

                    b.ToTable("tb_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@padrao.com.br",
                            IdCompany = 1,
                            Name = "Admin",
                            Password = "",
                            TypeUser = 0,
                            VerifiedEmail = false
                        });
                });

            modelBuilder.Entity("Model.Client", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Closure.Closures", b =>
                {
                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Closures")
                        .HasForeignKey("IdSalesman")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Model.Closure.ClosuresDetail", b =>
                {
                    b.HasOne("Model.Closure.Closures", "Closures")
                        .WithMany("ClosuresDetails")
                        .HasForeignKey("IdClosures")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Closures");
                });

            modelBuilder.Entity("Model.Moves.Box", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Boxes")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.Budget", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Budgets")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.BudgetItems", b =>
                {
                    b.HasOne("Model.Moves.Budget", "Budget")
                        .WithMany("BudgetItems")
                        .HasForeignKey("IdBudget")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Model.Moves.Financial", b =>
                {
                    b.HasOne("Model.Client", "Client")
                        .WithMany("Financials")
                        .HasForeignKey("IdClient");

                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Financials")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.CostCenter", "CostCenter")
                        .WithMany("Financials")
                        .HasForeignKey("IdCostCenter");

                    b.HasOne("Model.Moves.Box", "Box")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("Financials")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Moves.Sale", "Sale")
                        .WithMany("Financials")
                        .HasForeignKey("IdSale");

                    b.HasOne("Model.Moves.SaleItems", "SaleItems")
                        .WithMany("Financials")
                        .HasForeignKey("IdSaleItems");

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Financials")
                        .HasForeignKey("IdSalesman");

                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("Financials")
                        .HasForeignKey("IdService");

                    b.Navigation("Box");

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("CostCenter");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("SaleItems");

                    b.Navigation("Salesman");

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Moves.PlanCompany", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithOne("PlanCompany")
                        .HasForeignKey("Model.Moves.PlanCompany", "IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.Sale", b =>
                {
                    b.HasOne("Model.Client", "Client")
                        .WithMany("Sale")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Sale")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Sale")
                        .HasForeignKey("IdSeller");

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Model.Moves.SaleItems", b =>
                {
                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Moves.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("SaleItems")
                        .HasForeignKey("IdService");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Moves.ServicesProvision", b =>
                {
                    b.HasOne("Model.Moves.Budget", "Budget")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("IdBudget");

                    b.HasOne("Model.Client", "Client")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("ServiceProvisions")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Moves.ServicesProvisionItems", b =>
                {
                    b.HasOne("Model.Moves.ServicesProvision", "ServiceProvision")
                        .WithMany("ServicesProvisionItems")
                        .HasForeignKey("IdServiceProvision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvision");
                });

            modelBuilder.Entity("Model.Moves.SharedCommission", b =>
                {
                    b.HasOne("Model.Registrations.CostCenter", "CostCenter")
                        .WithMany("SharedCommissions")
                        .HasForeignKey("IdCostCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Moves.SaleItems", "SaleItems")
                        .WithMany("SharedCommissions")
                        .HasForeignKey("IdSaleItems")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("SharedCommissions")
                        .HasForeignKey("IdSalesman")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostCenter");

                    b.Navigation("SaleItems");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Model.Moves.Stock", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Stocks")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Model.Registrations.Commission", b =>
                {
                    b.HasOne("Model.Registrations.CostCenter", "CostCenter")
                        .WithMany("Commissions")
                        .HasForeignKey("IdCostCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Product", "Product")
                        .WithMany("Commissions")
                        .HasForeignKey("IdProduct");

                    b.HasOne("Model.Registrations.Salesman", "Salesman")
                        .WithMany("Commissions")
                        .HasForeignKey("IdSalesman")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("Commissions")
                        .HasForeignKey("IdService");

                    b.Navigation("CostCenter");

                    b.Navigation("Product");

                    b.Navigation("Salesman");

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Registrations.CostCenter", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("CostCenters")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.DescriptionFiles", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("DescriptionFiles")
                        .HasForeignKey("idCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.DetailsService", b =>
                {
                    b.HasOne("Model.Registrations.ServiceProvided", "ServiceProvided")
                        .WithMany("Details")
                        .HasForeignKey("IdServiceProvided")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvided");
                });

            modelBuilder.Entity("Model.Registrations.File", b =>
                {
                    b.HasOne("Model.Registrations.DescriptionFiles", "DescriptionFiles")
                        .WithMany("Files")
                        .HasForeignKey("IdDescriptionFiles")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DescriptionFiles");
                });

            modelBuilder.Entity("Model.Registrations.PhasesProspects", b =>
                {
                    b.HasOne("Model.Registrations.Prospects", "Prospects")
                        .WithMany("PhasesProspects")
                        .HasForeignKey("IdProspects")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prospects");
                });

            modelBuilder.Entity("Model.Registrations.Product", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.Prospects", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Prospects")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.Salesman", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Salesmen")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Registrations.ServiceProvided", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("ServiceProvideds")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.HasOne("Model.Registrations.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Model.Client", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("Sale");

                    b.Navigation("ServiceProvisions");
                });

            modelBuilder.Entity("Model.Closure.Closures", b =>
                {
                    b.Navigation("ClosuresDetails");
                });

            modelBuilder.Entity("Model.Moves.Box", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Model.Moves.Budget", b =>
                {
                    b.Navigation("BudgetItems");

                    b.Navigation("ServiceProvisions");
                });

            modelBuilder.Entity("Model.Moves.Sale", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Model.Moves.SaleItems", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("SharedCommissions");
                });

            modelBuilder.Entity("Model.Moves.ServicesProvision", b =>
                {
                    b.Navigation("ServicesProvisionItems");
                });

            modelBuilder.Entity("Model.Registrations.Company", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("Budgets");

                    b.Navigation("Clients");

                    b.Navigation("CostCenters");

                    b.Navigation("DescriptionFiles");

                    b.Navigation("Financials");

                    b.Navigation("PlanCompany");

                    b.Navigation("Products");

                    b.Navigation("Prospects");

                    b.Navigation("Sale");

                    b.Navigation("Salesmen");

                    b.Navigation("ServiceProvideds");

                    b.Navigation("ServiceProvisions");

                    b.Navigation("Stocks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Model.Registrations.CostCenter", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Financials");

                    b.Navigation("SharedCommissions");
                });

            modelBuilder.Entity("Model.Registrations.DescriptionFiles", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Model.Registrations.Product", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Financials");

                    b.Navigation("SaleItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Model.Registrations.Prospects", b =>
                {
                    b.Navigation("PhasesProspects");
                });

            modelBuilder.Entity("Model.Registrations.Salesman", b =>
                {
                    b.Navigation("Closures");

                    b.Navigation("Commissions");

                    b.Navigation("Financials");

                    b.Navigation("Sale");

                    b.Navigation("SharedCommissions");
                });

            modelBuilder.Entity("Model.Registrations.ServiceProvided", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("Details");

                    b.Navigation("Financials");

                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
