=== CONFIGURANDO SKIASHARP PARA LINUX ===
? Native library path found: /home/viniciu/workSpaceServiceBox/backEnd/WebApiCommercial/WebApiCommercial/bin/Debug/net9.0/runtimes/linux-x64/native
? Native library path found: /home/viniciu/workSpaceServiceBox/backEnd/WebApiCommercial/WebApiCommercial/bin/Debug/net9.0/
? Native library path found: /usr/lib
? Native library path found: /usr/local/lib
? LD_LIBRARY_PATH set to: /home/viniciu/workSpaceServiceBox/backEnd/WebApiCommercial/WebApiCommercial/bin/Debug/net9.0/runtimes/linux-x64/native:/home/viniciu/workSpaceServiceBox/backEnd/WebApiCommercial/WebApiCommercial/bin/Debug/net9.0/:/usr/lib:/usr/local/lib
? Found SkiaSharp libs: libSkiaSharp.pdb, libSkiaSharp.dll, libSkiaSharp.so, libSkiaSharp.so, libSkiaSharp.so, libSkiaSharp.pdb, libSkiaSharp.dll, libSkiaSharp.dylib, libSkiaSharp.so, libSkiaSharp.pdb, libSkiaSharp.dll
=== CONFIGURA��O SKIASHARP COMPLETADA ===
? Permission mappings configured successfully!
START TRANSACTION;

CREATE TABLE "tb_nfeEvento" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NFeEmissionId" integer NOT NULL,
    "CompanyId" integer NOT NULL,
    "TipoEvento" integer NOT NULL,
    "DescricaoEvento" character varying(200),
    "NSeqEvento" integer NOT NULL,
    "ChaveAcesso" character varying(44),
    "Correcao" text,
    "Protocolo" character varying(15),
    "CStat" integer,
    "XMotivo" text,
    "DhRegEvento" timestamp with time zone,
    "XmlEvento" text,
    "Situacao" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_tb_nfeEvento" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_nfeEvento_tb_company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES tb_company ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_tb_nfeEvento_tb_nfeEmission_NFeEmissionId" FOREIGN KEY ("NFeEmissionId") REFERENCES "tb_nfeEmission" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_tb_nfeEvento_CompanyId" ON "tb_nfeEvento" ("CompanyId");

CREATE INDEX "IX_tb_nfeEvento_NFeEmissionId_TipoEvento_Situacao" ON "tb_nfeEvento" ("NFeEmissionId", "TipoEvento", "Situacao");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260827115722_NFeEventoCartaCorrecao', '8.0.23');

COMMIT;


